# http://stackoverflow.com/questions/11068965/how-can-i-make-tmux-be-active-whenever-i-start-a-new-shell-session
# (dot-files note: xmonad can be and currently is configured to start a tmux
# session using the same solution as the above SO post, but it plays well with
# this, so that if you log into a TTY or similar you'll still automatically get
# a tmux session.)
#
# XXX: I've decided to not use this, because 1) I mainly use X / xmonad, where
# setup for this is already supported, and 2) quote:
#
# "However, there is a very small risk this can make bash behave in a way that
# other programs don't expect, since running bash can possibly cause it to
# turn into a tmux process, so it might be better to modify how you start your
# terminal emulator."
#
# UNCOMMENT TO START TMUX SESSION AUTOMATICALLY ONLY WHEN YOU HAVE BACKUP USER
# SET UP THAT CAN LOG INTO ROOT OR OTHERWISE HAS SUFFICIENT PERMISSIONS, TO FIX
# THINGS IF THEY BREAK.  THIS USER SHOULD *NOT* AUTOMATICALLY START TMUX
# SESSIONS, i.e. HAVE THIS ENABLED!
#
# UNCOMMENTING THIS MAY, IMMEDIATELY OR IN THE FUTURE, PREVENT YOU FROM
# STARTING YOUR zsh SHELL!
#if [[ ! $TERM =~ screen ]]; then
## TODO: lookup bash AND conditional.
#if [[ "$TMUX" = "" ]]; then
    #exec tmux new
#fi
#fi

export MYKEYID=XXXXXXXX
export EMAIL=email.address@example.com
